### ISSUE TITLE
Redesign profile tab and allow for an easier way to connect

### ISSUE THREAD

**Issue by mininao** [BDE-ESIEE/mobile#19]

**Comment by na-ji** [comment]
This tab would be useful for future parameters like notification subscriptions

**Comment by mininao** [comment]
Yes.

**Comment by kevin-ta** [comment]
It would be interesting to display our own FairPay balance on this tab.

**Comment by kevin-ta** [comment]
Commit [Added FairPay features on login tab](https://github.com/BDE-ESIEE/mobile/commit/8ea4e01d787234b5d45eee4ce8dd71808804595d)
