### ISSUE TITLE
Bug lors du DL de fichiers

### ISSUE THREAD

**Issue by mininao** [BDE-ESIEE/mobile#3]
Sur le téléphone de @vsalahkar , erreur suivante lors du clic sur un pdf :

![17195190_10212298301829581_157673645_o](https://cloud.githubusercontent.com/assets/5511564/23656660/e32115a6-033a-11e7-8157-fc455d063230.png)

**Comment by na-ji** [comment]
@vsalahkar : Tu as essayé d'ouvrir le lien avec quel navigateur ?
